/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWarehousingRouteImport } from './routes/services.warehousing'
import { Route as ServicesSourcingRouteImport } from './routes/services.sourcing'
import { Route as ServicesInspectionRouteImport } from './routes/services.inspection'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWarehousingRoute = ServicesWarehousingRouteImport.update({
  id: '/warehousing',
  path: '/warehousing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSourcingRoute = ServicesSourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInspectionRoute = ServicesInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/inspection': typeof ServicesInspectionRoute
  '/services/sourcing': typeof ServicesSourcingRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/inspection': typeof ServicesInspectionRoute
  '/services/sourcing': typeof ServicesSourcingRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/inspection': typeof ServicesInspectionRoute
  '/services/sourcing': typeof ServicesSourcingRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/services/inspection'
    | '/services/sourcing'
    | '/services/warehousing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/services/inspection'
    | '/services/sourcing'
    | '/services/warehousing'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/services/inspection'
    | '/services/sourcing'
    | '/services/warehousing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/warehousing': {
      id: '/services/warehousing'
      path: '/warehousing'
      fullPath: '/services/warehousing'
      preLoaderRoute: typeof ServicesWarehousingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sourcing': {
      id: '/services/sourcing'
      path: '/sourcing'
      fullPath: '/services/sourcing'
      preLoaderRoute: typeof ServicesSourcingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/inspection': {
      id: '/services/inspection'
      path: '/inspection'
      fullPath: '/services/inspection'
      preLoaderRoute: typeof ServicesInspectionRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesInspectionRoute: typeof ServicesInspectionRoute
  ServicesSourcingRoute: typeof ServicesSourcingRoute
  ServicesWarehousingRoute: typeof ServicesWarehousingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesInspectionRoute: ServicesInspectionRoute,
  ServicesSourcingRoute: ServicesSourcingRoute,
  ServicesWarehousingRoute: ServicesWarehousingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
